# Written by Lefteris kotsonis and Ilyass Taouil.
# Modeling Realsense D435 Sensor Noise for Improved 3D Reconstruction and Tracking.
input_sources:
  camera: # A name to identify the input source
    type: pointcloud # Supported types: pointcloud
    topic: /camera/depth/points # your topic
    queue_size: 1
    publish_on_update: true
    sensor_processor:
      ignore_points_above: 10.0
      ignore_points_below: -10.0
      cutoff_min_depth: 0.2
      cutoff_max_depth: 21
      type: structured_light # https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8768489
      normal_factor_a: 0.001063
      normal_factor_b: 0.003949
      normal_factor_c: 0.0
      normal_factor_d: 0.0008278
      normal_factor_e: 1
      lateral_factor: 0.01576 # approx 1 deg